### ISSUE TITLE
Cannot Build PGP signiture mismatch. 

### ISSUE THREAD

**Issue by drlamb** [gunzy83/linux-xps13-archlinux#5]
I tried installing this kernel on antergos using yaourt only to find that make fails to continue after the package's PGP signature cannot be verified.

**Comment by gunzy83** [comment]
Sorry about the slow response, I have been on holidays.

I am just about to issue another update that adds an array of valid pgp keys so that makepkg will trust that the author of the PKGBUILD has verified the key. Even with that you still need to add the PGP key to your keyring with the following commands:
```shell
# Ge the key:
gpg --recv-key $KEYID
# Check the key
gpg --search-keys $KEYID
# Trust the key
gpg --lsign $KEYID
```
Alternatively, uncomment this line:
```shell
# keyserver-options auto-key-retrieve line
```
in ~/.gnupg/gpg.conf to automatically download trusted keys (if the validpgpkeys array was not included in the package build this would not work).

Please see here for more details on the pacman and makepkg pgp changes:
http://allanmcrae.com/2015/01/two-pgp-keyrings-for-package-management-in-arch-linux/

Let me know how the build of 3.18.5-1 goes.

Thanks.

**Comment by drlamb** [comment]
Unfortunately, I returned the laptop. The lack of Linux support out of the box was frustrating.

**Comment by gunzy83** [comment]
Fair enough. This laptop only ships with Ubuntu and the patch in this repo is similar to the patch Ubuntu make for this hardware (trackpad). Just out of interest, can I ask what support was lacking for you?
